### ISSUE TITLE
Uncaught type error in browser following clean installation

### ISSUE THREAD

**Issue by nefD** [Kocisov/wooo#2]
Upon creating a fresh project using create-react-app and and following the instructions for installing woo into this new directory, I get a "Uncaught TypeError: Cannot read property 'listen' of undefined" error in the Chrome dev tools console.

Reproduction steps:

~/somedirectory$ npm install -g redux-wooo
~/somedirectory$ create-react-app my-react-app
~/somedirectory$ cd my-react-app
~/somedirectory/my-react-app$ wooo -d ./src -n
~/somedirectory/my-react-app$ npm run start

**Comment by kocisov** [comment]
Hello.

The problem was in the react-router because it doesn't come with history dependency since version 4.
I fixed it with specifying a react-router version to be 3.0.2 instead of latest which is 4.0.0.

Thanks for reporting this.
